import React, { useState } from 'react';
import './App.css';

// Array of image paths and descriptions
const cardsData = [
  {
    image: '/images/fool.jpg',
    title: 'The Fool',
    description: "The Fool represents faith, hope, trust, and the journey toward self-growth and fulfillment. It symbolizes the potential for new beginnings and highlights the need for choices that align with personal aspirations. While life may currently feel unsettling or dissatisfying, this card encourages you to trust in the possibilities of a brighter future and take steps toward achieving it. On the family front, someone close may be seeking employment, and unexpected decisions or visits could arise, including a possible trip to see someone in the hospital. Relationships are marked by mixed emotions, as you navigate feelings of distrust or uncertainty. Whether romantic or platonic, connections that contribute to your growth will be cherished, while unproductive or unfulfilling relationships will be left behind. In career and finances, decisions loom large, with opportunities pointing toward public-facing roles, teaching, or entrepreneurship. While you might contemplate job changes or breaks, financial prospects look promising, though some paperwork or formalities may require significant effort before reaping rewards. The Fool advises embracing change as a means of emotional healing and personal independence, reminding you to let go of unproductive areas and prioritize authenticity. Challenges may arise, testing your patience and pushing you to confront situations beyond your control, but these experiences will ultimately lead to clarity, healing, and unexpected support from positive relationships. On the health front, fatigue or exhaustion may linger, yet you might hesitate to seek immediate solutions, instead exploring alternative methods for relief. Discussions around holistic or alternative healing could provide fresh perspectives. At home, decisions about significant changes, such as relocation, may surface, but for now, you are likely to choose stability over drastic moves. The Fool signifies that even in uncertainty, growth and optimism are within reach if you remain open to learning from the journey and taking leaps of faith toward your true potential.  ",
  },
  {
    image: '/images/magician.jpg',
    title: 'The Magician',
    description: "The Magician embodies the power of new beginnings, opportunities to showcase talents, and the ability to shape your destiny. It signifies a time of transformative action, where you desire to embark on something new, hoping for a miracle to manifest positive change. As you move forward, a fresh start awaits, aligning with your aspirations and wishes. Within your family, you may need to address changes or take decisive actions involving relatives, especially if you feel underappreciated or hurt. Asserting your needs and setting boundaries are crucial, though a friend's guidance and support will provide reassurance. In relationships, a significant shift looms, with either a new romantic connection or a revitalized existing bond promising happiness and delightful surprises. For those in partnerships, mutual interests, open communication, and friendship form the foundation, yet unspoken resentments or communication breakdowns could create barriers. Resolving these issues will help avoid misattributions of blame. Financially, prosperity is on the horizon, with opportunities for successful partnerships, lucrative ventures, and career advancements. Exam success, landing a great job, or entrepreneurial achievements are likely, along with profitable financial transactions and ideas that enhance your career or business. Increased motivation will attract success, resulting in significant income growth. However, maintaining patience and avoiding overexertion is essential. Others may attempt to dominate or take you for granted, so asserting yourself consistently is key. Success awaits in creative pursuits, projects, and independent endeavors, while an important financial letter will require prompt action. Health-wise, stress might take a toll, and minor ailments could be difficult to diagnose or treat effectively, emphasizing the need to unwind and relax. Travel plans may face postponements or adjustments, but you will enjoy an invitation to a pleasant social gathering. At home, stability is preferable for now; property sales or offers will proceed positively, ensuring eventual resolution. Overall, The Magician encourages self-belief, purposeful action, and embracing opportunities, paving the way for personal and professional growth.",
  },
  {
    image: '/images/high_priestess.jpg',
    title: 'The High Priestess',
    description: "The High Priestess embodies patience, learning, and the unveiling of hidden truths, particularly in areas like finance, trade, public relations, and personal relationships. While you may face frustrations at work or encounter emotionally complex situations, persistence will lead to smoother outcomes and unexpected rewards. Family dynamics might feel isolating or challenging, but your intuition and insight can guide you toward positive resolutions. Relationships may reach a crossroads, requiring patience and honest communication to strengthen bonds or gain clarity about moving on. Financially, slow beginnings will give way to profitable opportunities, such as bonuses, unexpected job offers, or career advancements, though caution is advised against unethical dealings in the workplace. Trusting your instincts will help you make wise decisions, but patience is key as progress unfolds. Health improvements are likely if you’ve been unwell, though emotional stress may stem from high expectations of yourself and others. Short trips or work-related travel may arise, but long-distance plans could face delays. In decisions about property, determination will ensure success once clarity is achieved. Overall, The High Priestess encourages embracing your intuitive strengths, navigating challenges with patience, and remaining open to surprising opportunities for growth and transformation.",
  },
  {
    image: '/images/empress.jpg',
    title: 'The Empress',
    description: "The Empress represents emotions, self-expression, and the desire for fulfillment, urging you to address feelings of discontent by identifying what truly brings joy and meaning to your life. You may feel misunderstood by family or friends, particularly a female relative, and could face delays or communication issues involving property transactions. Clarifying your intentions and taking thoughtful action can resolve these strains. In relationships, you crave love and affection but may struggle to express your desires. This card signals the potential for long-term commitment, family growth, or pregnancy, but challenges like feeling stuck, financial stress, or unmet expectations may arise. Patience and understanding can strengthen your bond, even during trying times. Financially, delays or confusion might require you to postpone transactions, review contracts carefully, and seek advice. Missed communications, like bills or letters, could demand your attention, but upcoming resolutions will ease stress. Guidance from The Empress suggests that embracing nature, relaxation, and a positive attitude will help life flow more smoothly. Taking time for yourself, whether through a vacation, hiking, or simply enjoying the outdoors, will rejuvenate your mind and body. Sharing acts of kindness, like giving or receiving a thoughtful gift, will foster goodwill and connection. Healthwise, rest and a natural diet can enhance your physical and mental well-being. Travel and work may intertwine, bringing opportunities to explore new environments or search for a home. If considering country living, it promises peace and tranquility to soothe your spirit. Embrace The Empress’s energy to nurture your emotional, physical, and creative self while cultivating positivity and harmony in your life.",
  },
  {
    image: '/images/emperor.jpg',
    title: 'The Emperor',
    description: "The Emperor signifies stability, structure, and transformation, suggesting that a significant person or opportunity may soon reshape your current circumstances, offering new paths in partnerships or relationships. This change could fulfill long-held desires, especially related to material gains or emotional connections. Within the family, a dominant figure may exert influence, leading to tensions or untruthfulness, but support from friends, particularly male ones, will provide comfort. In relationships, couples may plan for a future together, while singles may enter a passionate and rewarding connection. If leaving an unsatisfactory relationship, you’ll decisively move forward. Financially, expect discussions about contracts or new ventures to result in increased income, enabling you to indulge in luxuries. Challenges will soon resolve, with opportunities paving the way for a fulfilling future. Attend social events, as they may bring unexpected joy and fortune. Health concerns, whether yours or a partner’s, are likely unwarranted, and recovery from illness will be swift. Travel plans may face delays due to work or legal matters, but home-related goals, such as buying or selling property, will see significant progress and financial success. Embrace the transformative energy of The Emperor to create stability and achieve your aspirations.",
  },
  {
    image: '/images/heiro.jpg',
    title: 'The Hierophant',
    description: "The Hierophant symbolizes tradition, truth, and structure, urging you to address restrictive bonds and seek deeper understanding. It’s a time to stand firm against manipulation or disrespect and prioritize self-worth. Within family dynamics, you might avoid conflict to maintain peace, but unresolved issues will eventually require confrontation. Miscommunication could lead to misunderstandings with loved ones, necessitating patience and clarity. In relationships, dissatisfaction may prompt a choice between improving the bond or moving on. For singles, high standards might delay romance, though meaningful partnerships, including marriage, are possible. Financially, challenges at work or in business may lead to reevaluation and eventual alignment with your values, even if initial efforts falter. Guidance may come from introspection or unexpected sources, emphasizing the importance of staying true to your principles. Health concerns, especially stress-related, may require medical attention. Travel plans might face confusion or obstacles but remain necessary for communication or idea exchange. Home projects, however, could proceed favorably with good deals on renovations. The Hierophant encourages growth through truth, discipline, and meaningful change.",
  },
  {
    image: '/images/lovers.jpeg',
    title: 'The Lovers',
    description: "The Lovers card embodies choice, union, and transformation, often tied to relationships, decisions, and sudden changes. It calls for clarity, especially when facing dilemmas in love, family, or personal pursuits. In family matters, tensions may arise from unequal responsibilities, requiring communication and firm boundaries to resolve them, while relatives may face challenges with property or repairs. Relationships could bring both challenges and opportunities, with separations leading to new, meaningful connections, and romantic bonds deepening into lasting commitments. Financial disappointments may redirect efforts toward unexpected success, particularly in trade or documentation, while income from commissions or specialized skills will cover financial needs. Social opportunities will soon emerge, bringing joy and new connections, while health improvements will boost confidence if you decide to make changes. At home, productivity is high, with successful property sales or repairs, though vigilance is needed regarding faulty appliances or equipment. The Lovers urge thoughtful choices, alignment with your values, and openness to life’s opportunities for growth and fulfillment.",
  },
  {
    image: '/images/chariot.jpg',
    title: 'The Chariot',
    description: "The Chariot signifies introspection, re-evaluation, and the need for clarity amidst confusion. It indicates a period where you may feel overwhelmed by your circumstances, unsure of your direction, and afraid of losing control. Attempting to force a resolution may only worsen the situation, and it's only when you let go that things will improve. Family matters may bring unexpected challenges that cause irritation, but you will overcome them and reassess your values, even though outwardly it may seem unchanged. Relationship dynamics may include confrontations with a partner or difficulties expressing your feelings, requiring self-reflection to improve communication. For singles, fear of vulnerability may lead to superficial connections, but gifts or tokens of affection will show progress toward deeper commitment. Financially, you may face dilemmas but will be driven to pursue opportunities, leading to eventual success. A confrontation over money owed will be resolved in your favor. Guidance suggests that confusion will soon be replaced by clarity and insight, helping you change attitudes and find peace with past wounds. Socially, expect some lively and flirtatious times, and business opportunities will soon arise, bringing financial growth. Health-wise, it's important to slow down and avoid burnout, as mental and physical exhaustion may result from stress.",
  },
  {
    image: '/images/strength.jpg',
    title: 'Strength',
    description: "Strength focuses on overcoming challenging situations, particularly in business, finance, and family matters. It suggests that past issues or disappointments may be causing stagnation in love, business, or relationships, but this is a temporary phase. Positive changes are coming that will bring renewed power and control to your life. Family dynamics may involve unexpressed resentments, but these will be resolved in your favor. If considering a union or marriage, expect joy and positivity, though past emotional attachments may make you hesitant. Financial dilemmas will be resolved, with recognition and rewards for your efforts, improving your financial situation and work prospects. Obstacles will be overcome with ease, and you will find yourself guided through challenges. An unexpected phone call may bring news of an increase in income or recognition. Health-wise, your energy will be vibrant, and recovery from illness will be swift. You may take short trips, and any home renovations or changes you plan will be carried out successfully.",
  },
  {
    image: '/images/hermit.jpg',
    title: 'The Hermit',
    description: "The Hermit card represents seeking insight, completing phases, and problem-solving. It indicates a time of transition, where an old phase of your life ends, and a new one begins. While feelings of sadness or apprehension may arise due to a sudden loss, things will soon change, bringing relief and accomplishment. Family matters suggest that the completion of a cycle will lead to the resolution of sadness, and you may reconnect with a distant relative or an old friend. If you've had conflicts in your love life, expect a reconciliation. Financially, you may face issues regarding insurance or career instability, but recognition and financial success are on the horizon. Guidance suggests optimism, as isolation or restrictions will soon end, bringing a brighter future. Approach challenges with grace, not force, and trust that better conditions are ahead. In terms of health, mysterious symptoms may stem from emotional suppression, and addressing this will improve your well-being. Travel-wise, you're considering a major trip or move, while home life may involve selling property or experiencing shifts that take you out of your home more often.",
  },
  {
    image: '/images/wheel_of_fortune.jpg',
    title: 'Wheel of Fortune',
    description: "The Wheel of Fortune card signifies the onset of unexpected changes, mood swings, and important news that may alter the course of your life. These fluctuations are often tied to unresolved work or personal matters that make it hard to maintain emotional stability. Family matters might bring some strain, particularly with a loved one falling ill or a family member becoming a constant source of agitation. Despite these challenges, any rifts within the family will eventually be resolved through compromise and mutual understanding. In relationships, you might experience disappointments or uncertainty, especially if someone from the past reappears, leaving you conflicted about the future of your connection. The pursuit of love could feel elusive for a while, but the end of negative conditions will pave the way for a new chapter. Financially, the card indicates that while your current work situation may not be fulfilling and your finances might be in decline, a shift in fortune is on the horizon. Important news will shed light on these financial concerns, providing a renewed sense of hope. There may be a new business opportunity or a significant financial breakthrough. Guidance suggests that while you've faced isolation or loneliness, a new transition will soon begin, bringing with it positive changes. Any changes you make to your career, health, or personal life will be beneficial, and you will likely achieve the goals you set for yourself. Additionally, your ability to teach or enlighten others may come to the forefront, opening up new opportunities. Health-wise, if you've been considering a checkup, the results will be favorable. Travel is also indicated, with work or study-related trips on the horizon. Finally, the card suggests that changes in your home or living situation are likely, possibly due to increased financial obligations or dissatisfaction with your current space. You might feel the need to relocate or make significant adjustments to your home life. Overall, while there are emotional and financial hurdles to overcome, the **Wheel of Fortune** assures that the challenges are temporary and that positive shifts are on the way, leading to better circumstances and a renewed sense of purpose.",
  },
  {
    image: '/images/justice.jpg',
    title: 'Justice',
    description: "The Justice card highlights themes of fairness, balance, and resolving dilemmas, particularly in matters of legal issues, income, and achieving personal goals. It suggests that you may be grappling with an unresolved issue, whether in business or personal life, and that patience is required before a resolution can be reached. Family matters may be particularly challenging, with a relative possibly experiencing difficulties in their relationships, such as separation or divorce. You might find yourself being the mediator, working to resolve conflicts and bring peace within the family. In relationships, you’ll be assessing the quality of your life and connections, and you may realize that you seek more meaningful bonds. Although you may still feel a sense of isolation, the **Justice** card brings a sense of reconciliation, where past disagreements or misunderstandings are resolved, making way for a more flexible and harmonious relationship. If you are dealing with a romantic connection, this could signify a turning point where the relationship either strengthens through mutual understanding or faces a parting of ways. Financially, the card promises a new business opportunity and suggests that financial struggles are coming to an end. You will find that your financial obligations are gradually being cleared, and you’ll come to the right decisions to resolve monetary concerns. Justice also indicates that you’re about to enter a new cycle, one that will offer clarity and understanding of your true needs and desires. You may feel that destiny or fate is at play in your life, but with time, the truth of the situation will be revealed. While you may feel temporarily powerless, the **Justice** card reassures you that support will arrive, either through a kind gesture or a legal matter that works in your favor. In health, you might need dental treatment or medical advice, and a second opinion will likely confirm that your concerns are valid. Travel may also be on the horizon, with a move or journey that will lead to new experiences. Lastly, the **Justice** card suggests dissatisfaction with your current home or living situation, urging you to seek a change that aligns with your evolving needs and personal growth. This card ultimately serves as a reminder that balance, fairness, and clarity will prevail, guiding you toward positive change.",
  },
  {
    image: '/images/hanged_man.jpg',
    title: 'The Hanged Man',
    description: "The Hanged Man card reflects a time of introspection, feeling stuck, and seeking clarity, often associated with periods of confusion, self-doubt, and a lack of direction in life. You may feel that your efforts have been in vain or that your dreams no longer hold meaning, leaving you anxious and uncertain about the future. There's a sense of helplessness, as you wait for others to act or make decisions, feeling that control has slipped out of your hands. In family matters, this card suggests a period of reflection, where you may receive unexpected help or comfort from a relative or friend. A visit or stay at their home may bring peace and provide support for new ventures. However, you may also experience feelings of sadness or regret, particularly regarding unresolved issues with a family member. In relationships, the **Hanged Man** may indicate emotional restriction or dissatisfaction, especially in your marriage or partnerships. You might feel that the love or connection has become obsolete, and there’s a struggle to either change or end it. Despite these challenges, there’s hope that the situation will eventually resolve itself for the better. When it comes to finances, the **Hanged Man** suggests concerns about the value of your work or financial sustainability. Yet, despite these worries, the card promises a fortunate turn of events, with repeat clients, financial growth, and opportunities that will improve your situation. It's a time to carefully examine legal documents or contracts to avoid misunderstandings. Guidance from this card encourages patience and an open mind. Though emotional reactions may cloud your judgment, the path ahead will begin to clarify, offering new perspectives, and a positive change in direction. This period of reflection will bring new inspiration, purpose, and even a beneficial gift or awaited letter. Health-wise, rest and self-care are needed to regain energy and reduce the restlessness you’re feeling. The **Hanged Man** also suggests a short trip to a new environment, though be cautious of unexpected setbacks or travel disruptions. Overall, this card marks a phase of waiting, reflecting, and preparing for future transformation.",
  },
  {
    image: '/images/death.jpg',
    title: 'Death',
    description: "The Death card is a powerful symbol of endings and new beginnings, signaling a significant period of transformation in various aspects of life. You may be feeling overwhelmed or disheartened by recent events, sensing that circumstances are pushing you toward change, whether you're ready or not. This card often indicates a time of emotional unrest, where you might feel as though your hopes and expectations were dashed, particularly regarding your career or relationships. However, **Death** encourages you to release what no longer serves you. Holding on to outdated situations or beliefs will only leave you isolated and stagnant. In family matters, there is a sign of reunion, as a happy gathering with loved ones may soon take place, bringing comfort and healing during this time of transition. In relationships, the **Death** card often heralds the end of a chapter, whether it's the conclusion of a romantic relationship or the recognition that a connection has run its course. While this realization can be painful, it is necessary for personal growth, as it paves the way for renewal and empowerment. Financially, you may face unexpected challenges, such as a loss of income or business setbacks, causing worry and uncertainty. However, this card assures that if you've lost something important, new opportunities will soon emerge, bringing luck and financial recovery. The **Death** card also indicates that a radical shift is on the horizon. You might feel that your current circumstances can no longer continue, and the changes that are coming will be profound and necessary for your evolution. Though these changes may initially seem uncomfortable, they will ultimately lead to a stronger and more fulfilling future. Health-wise, the **Death** card suggests that improvements are possible through a change in mindset and attitude, and by embracing a healthier perspective, you will find that your overall well-being improves. If you're planning a trip, expect a delay in your travel plans, but it will ultimately lead to a new and meaningful experience. In terms of your home, you may be considering relocating or embarking on new home-related projects that will bring fresh energy into your living space. Overall, the Death card signifies the end of one phase and the beginning of another, marking a period of profound transformation and renewal.",
  },
  {
    image: '/images/temperance.jpg',
    title: 'Temperance',
    description: "The Temperance card signals a time of balance and moderation, but it also warns that unresolved issues may resurface in various aspects of your life. Old problems, whether related to past relationships, health concerns, financial difficulties, or unresolved emotional baggage, may come back to test you. You may feel overwhelmed, like your emotions and desires are out of balance, and that you’ve reached a breaking point. Despite these feelings, **Temperance** encourages patience and composure, assuring that through discipline and balanced action, solutions will emerge. In family matters, tensions may arise that cause you to feel out of sync with those around you, especially when old health issues resurface. Yet, the card reminds you that support is available from loved ones who are willing to listen and help. In relationships, you might feel neglected or deceived by your partner, creating a sense of imbalance or disconnection. However, **Temperance** suggests that while you may feel the need for drastic change, it’s important to maintain composure and seek a healthy balance between your desires and your partner’s actions. You may encounter a person from your past, either rekindling an old connection or finally closing a chapter for good. Financially, you could be facing concerns about your stability or business prospects. However, **Temperance** indicates that through persistence and effort, you will begin to see a chain reaction leading to moderate success. It may require confronting someone regarding debts or paperwork, but a careful approach will prove successful. **Temperance** also brings guidance, suggesting that unforeseen events will test your patience, but you will emerge stronger by maintaining a level-headed approach. It’s important to reflect on your actions and avoid jumping to conclusions. People around you will show affection and support, helping you transform negative situations into positive ones. Health-wise, the card warns of stress, anger, and irritability, which can affect your well-being. To find balance, consider taking long walks to clear your mind and gain clarity. As for travel, ensure that all necessary paperwork is in order to avoid delays. If travel plans are postponed, it may be a sign that rest is needed for a more balanced approach to your journey. Ultimately, Temperance encourages patience, balance, and moderation to navigate challenges and find peace in a chaotic period.",
  },
  {
    image: '/images/devil.jpg',
    title: 'The Devil',
    description: "The **Devil** card symbolizes negative cycles, adversity, and confusion, often pointing to situations where you feel trapped or blocked in your pursuits. If you’re feeling overwhelmed and disheartened by continuous struggles, this card suggests that you may be seeing only part of the picture and could be unaware of the underlying forces holding you back. You might be contemplating withdrawing from a situation or giving up due to a lack of results despite your efforts. In family matters, you could find yourself bound to a loved one or friend who is causing emotional distress. Although it’s difficult to break free from their influence, forcing confrontation at this time will not lead to the resolution you seek. Instead, it’s important to avoid becoming negative or resentful, as this will only worsen your situation. In relationships, you may encounter obstacles preventing reconciliation with a past partner. You may still have deep feelings for them, but misunderstandings or emotional blockages may keep you from reconnecting. Some confrontations or arguments may arise with those close to you, and it’s possible they will have the upper hand in these disputes. Financially, **The Devil** card warns of a negative state of mind, particularly related to work or money. You may feel burdened by too much work for too little gain, leading to frustration and irritation. Unexpected financial difficulties, such as bad investments or overdue bills, may also appear, though an opportunity to make more money will eventually arise. However, a business venture may fail due to external circumstances beyond your control. It’s important to avoid rushing ahead without planning or acting impulsively, as this could worsen the situation. The **Devil** card urges patience and self-control, allowing time for clarity and progress. Health-wise, the card suggests that stress and exhaustion are taking their toll, leading to trouble sleeping and burnout. A slower pace and possibly beginning an exercise routine will help relieve some of this pressure. In terms of travel, there’s an indication that plans will be delayed due to unforeseen circumstances. Finally, in matters of home or relocation, **The Devil** warns against making impulsive decisions; waiting for a more positive situation will bring better results in the long run. The key message is to exercise patience and avoid being caught in the negative cycles that seem to bind you.",
  },
  {
    image: '/images/tower.jpg',
    title: 'The Tower',
    description: "The Tower card is a powerful symbol of sudden, unexpected change, often characterized by upheaval and destruction, which can initially seem unsettling or catastrophic. This card signals the collapse of long-standing structures or beliefs that are no longer serving you, whether they relate to your personal life, career, relationships, or even your understanding of the world. While it may appear as a disaster, the Tower card is not a harbinger of doom; instead, it presents a necessary cleansing of the old to make way for new growth. This breakdown, though painful, offers an opportunity for liberation, as it forces you to confront uncomfortable truths and false assumptions that have been holding you back. When the Tower strikes, it often brings about major disruptions that are beyond your control, such as the end of a significant relationship, the loss of a job, financial setbacks, or a sudden revelation that shakes your perception of reality. These events, though distressing, are essential to your personal evolution. They strip away illusions, showing you the truth, no matter how harsh, and challenging you to rebuild from a more grounded and authentic place. In relationships, the Tower can signal shocking revelations, hidden secrets coming to light, or the unraveling of bonds that were once thought to be solid. If you’ve been holding onto something or someone out of habit, fear, or denial, the Tower may force you to release these attachments, no matter how difficult it is. Financially, the Tower warns against making risky investments or taking chances, as sudden financial loss is often indicated. However, this loss can serve as a catalyst for a deeper understanding of your financial goals, leading you to reevaluate how you approach money and success. On a health level, the Tower might indicate physical or mental strain, a wake-up call to pay attention to your well-being. While the events brought by the Tower can feel like a personal crisis, they are also opportunities for profound transformation. The destruction of old systems opens the door to new opportunities, allowing you to rebuild from a place of strength, clarity, and renewed purpose. Embrace the change, for it is often in the midst of chaos that we find the clarity to create something truly meaningful.",
  },
  {
    image: '/images/stars.jpeg',
    title: 'The Star',
    description: "The Star card signifies hope, inspiration, and the potential for a brighter future. It represents a period when you might feel hurt or disappointed by harsh words or circumstances that block your personal growth. You may experience feelings of estrangement or an inability to move forward in your work and personal life, prompting a deep desire for change or improvement. This card signals a yearning for a sense of meaning, purpose, or inspiration that could reignite your passion and drive. You may wish for your future to surpass the difficulties or challenges of your past. In family matters, this card indicates that someone in your close circle may face difficulties with legal matters or document-related issues. However, you will find solace in the supportive presence of friends and family, who will offer advice and insights, helping you work through your problems. Relationships may also be a focal point, as the card suggests a strong emotional connection or karmic tie with someone that might be difficult to sever. If you are feeling unfulfilled or lacking in love, The Star card encourages you to remain hopeful, as your desires will eventually be fulfilled. You may find inspiration from someone new, whose presence or energy will bring meaning and renewal to your life. Financially, the Star card indicates a period of progress, especially in professional goals. You may be involved in paperwork that connects your past with the present, helping you clarify your goals and expand your business or career prospects. Expect good news, advice, or calls related to financial gains or opportunities. In terms of guidance, The Star reveals that someone or something will provide valuable insights into your future, helping you reassess your life path and consider new possibilities. As negative situations start to dissipate, you will find yourself receiving help from mentors, friends, or advisors. Financially, a windfall may be on the horizon, whether through unexpected gifts, lottery wins, or new opportunities. You may also experience a spontaneous spending spree, where you indulge in items that bring you joy. In health matters, you might decide to take charge of your well-being by scheduling medical check-ups or committing to a fitness regimen. Finally, in terms of your home or property, The Star suggests that if you're looking to sell, lease, or manage real estate, you'll see progress and opportunities arise. The card encourages you to remain hopeful and optimistic about the future, as positive changes are on the way.",
  },
  {
    image: '/images/moon.jpg',
    title: 'The Moon',
    description: "The Moon card represents a period of inner turmoil, confusion, and disillusionment, often arising from deceptive or unstable situations that challenge your emotional resilience. You may feel crushed by disappointment, as someone or something you relied upon has let you down, leaving you devastated and uncertain. Harsh words, unmet expectations, or unforeseen challenges may exacerbate these feelings, creating a sense of being lost or overwhelmed. In family matters, plans to collaborate on a home project or host a gathering could lead to emotional setbacks, leaving you disheartened by the lack of support or the emergence of upsetting conditions. However, these difficulties can also pave the way for growth and a more balanced perspective. In relationships, you may feel disoriented by unmet expectations or conflicts, finding it difficult to navigate your emotions. Messages or interactions with loved ones could bring disappointment, but they also push you to confront your feelings and seek clarity. Financially, unforeseen challenges at work or delays in important matters, such as payments or contracts, may leave you feeling cheated or shortchanged. What initially seems promising might devolve into a test of endurance, yet new opportunities and group efforts will emerge, helping you recover after significant changes are addressed. The card’s guidance emphasizes the importance of facing these challenges head-on, accepting situations as they are, and allowing transformation to occur naturally. By doing so, you will free yourself from the anxieties of failure, loss, or unmet expectations, emerging stronger and more resilient. Health concerns may manifest as physical or emotional disturbances, such as insomnia, strange dreams, or feelings of disorientation, highlighting the need for rest and mindfulness. Travel plans may be disrupted by unforeseen problems or unpleasant circumstances, leaving you wishing you hadn’t embarked on the journey. At home, delays or setbacks in renovation projects, property matters, or promised support may lead to feelings of disillusionment. Despite these challenges, The Moon encourages introspection and perseverance. Accepting the reality of your situation, rather than resisting it, will bring about transformative growth, enabling you to find clarity, balance, and hope. Ultimately, this period of uncertainty will give way to a brighter and more positive future, as something you believed lost, impossible, or irreparable is revived or replaced, leaving you with renewed strength, happiness, and success.",
  },
  {
    image: '/images/sun.jpg',
    title: 'The Sun',
    description: "The focus here revolves around society, public image, accomplishments, and personal unions such as marriage or mergers. Despite external appearances, you may feel emotionally drained and unfulfilled, yearning for a deeper connection or meaningful achievement. Within the family, a short visit from a relative may bring interaction, but their apparent disinterest could leave you feeling unimportant. Relationships carry a mix of hope and uncertainty, especially if you are yearning for someone special or navigating a separation. Though you may not connect with the person your heart desires, others may enter your life seeking your attention. Financial matters present challenges with legal documents, contracts, and a lack of enthusiasm for work. However, relief comes through favorable resolutions, such as financial settlements, unexpected favors, or promotional opportunities. The guidance suggests being cautious about mixing business with friendship and maintaining patience as delayed plans eventually come to fruition. You might be offered public speaking engagements or other professional prospects that bring financial rewards. Emotionally, you may mask your true feelings, appearing content despite inner dissatisfaction. Simple pleasures with friends or social outings provide fleeting joy but come with high expenses, including an unreasonable bill. A lack of self-love might prompt you to consider changes to your appearance, such as a new hairstyle or wardrobe. Professionally, ideas for new ventures could take shape, and partnerships or tempting offers may arise, possibly involving legal discussions. Keep an open mind to recognize truths that lead to clarity and resolution. Gratitude for second chances and existing blessings will provide comfort and perspective. In terms of health, feelings of exhaustion and being run-down indicate the need for rest and self-care. You might embark on a fitness program or other initiatives to improve your well-being. Travel plans could prove disappointing or unproductive, leaving you regretting the effort. At home, aesthetic improvements and a general facelift may be on the horizon, signaling a desire for a refreshed environment. Additionally, calls regarding new housing opportunities may present themselves. Ultimately, despite present struggles or disillusionment, remaining patient, open-minded, and grateful for what you have will help you navigate this period of emotional and practical challenges toward eventual renewal and success.",
  },
  {
    image: '/images/judgement.jpg',
    title: 'Judgement',
    description: "The theme of Judgement focuses on renewal, new beginnings, and transformative opportunities, both in personal and professional realms. This phase signifies the arrival of new relationships, ventures, and supportive alliances that improve conditions and bring clarity to past uncertainties. However, challenges may arise, such as unexpected confrontations or financial disputes, urging you to reassess your priorities and let go of the past to move forward. Within the family, nurturing support and uplifting news from relatives will provide comfort. An unexpected visitor is also likely, bringing a sense of connection and surprise. Relationships are marked by transitions; as you distance yourself from past attachments, nostalgia and sadness may linger, but these feelings are part of the process of healing and growth. Actions or attitudes from someone in your life may lead you to question whether to rekindle or continue the relationship. Financially, improvements are on the horizon, with gains from settlements, judgments, or long-standing debts being resolved. New inspiration will breathe life into previously stalled endeavors, and business ventures will yield rewarding outcomes. These changes will provide much-needed motivation and a sense of direction. Guidance comes in the form of resolving internal and external conflicts, marking the end of confusion and emotional struggle. Self-development and shifts in perspective will lead to renewed purpose and enthusiasm. A sudden, unexpected situation may alter your plans or feelings, particularly in romantic matters, but this will ultimately lead to positive outcomes and a sense of progress. Embrace opportunities that arise, as they hold the potential to transform your life significantly. You may even receive a symbolic gift, such as roses, or a letter involving financial matters linked to the past. Uplifting news will act as a turning point, offering a chance for renewal and hope. Health-wise, there may be concerns about a loved one’s illness or minor issues like dizziness for yourself, possibly tied to dietary habits. On the travel front, a short trip could prove life-changing, offering significant encounters with someone who admires you or aids your professional pursuits. This period emphasizes embracing new opportunities, learning from the past, and being open to change, paving the way for meaningful progress and fulfillment in your life.",
  },
  {
    image: '/images/world.jpg',
    title: 'The World',
    description: "The theme of The World symbolizes significant challenges, transformative changes, and eventual breakthroughs, focusing on overcoming limitations, embracing opportunities, and addressing global or personal matters. You may feel burdened by external pressures, societal expectations, or unresolved personal issues, leading to frustration and an intense desire for liberation and success in all areas of life. Family dynamics could be strained, with burdensome in-laws, separations, or conflicts causing unhappiness, and a sense of being unsupported or used by friends or relatives might deepen feelings of isolation. Discussions surrounding loss, such as a breakup, divorce, or the passing of a loved one, could add emotional strain. In relationships, unmet expectations and preoccupation with the past may hinder progress, while irrational behaviors from loved ones could cause hurt and confusion. However, self-reflection will provide insights that lead to personal growth and the potential for renewal in future connections. Financially, while progress may feel temporarily blocked, significant improvements, new opportunities, and increased earnings will soon emerge, including unexpected sources of income like tax refunds or interest gains. Professional recognition and praise will further solidify a sense of accomplishment. Transformation and release are central themes, urging you to let go of past limitations, channel frustration constructively, and embrace new methods and perspectives for success. Although feelings of discontent or the urge to escape may surface, they can act as catalysts for meaningful change. Social interactions will prove rewarding, bringing recognition, support, and valuable opportunities. Health-wise, recovery from recent illnesses or injuries is highlighted, with the need to slow down and possibly seek additional medical advice. A spontaneous trip may arise, offering rejuvenation and the chance to alter your outlook and luck, making it a potentially life-changing experience. Overall, The World encourages overcoming adversity, embracing transformation, and finding fulfillment through resilience, self-awareness, and openness to new opportunities in personal and professional realms.",
  },
];



// Default back image for the cards
const defaultBackImage = '/images/back.jpg';

// Shuffle function
function shuffle(array) {
  return array.sort(() => Math.random() - 0.5);
}

function Card({ image, isRevealed, onClick }) {
  return (
    <div className="card" onClick={onClick}>
      <img src={isRevealed ? image : defaultBackImage} alt="Card" />
    </div>
  );
}

function Modal({ card, onClose }) {
  if (!card) return null;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content" onClick={(e) => e.stopPropagation()}>
        <button className="modal-close" onClick={onClose}>
          &times;
        </button>
        <div className="modal-body">
          <div className='modal-img'><img src={card.image} alt="Card" className="modal-image" /></div>
          <div className="modal-description">
            <h3>{card.title}</h3>
            <p>{card.description}</p>
          </div>
        </div>
      </div>
    </div>
  );
}




function App() {
  const [cards, setCards] = useState(shuffle([...cardsData]));
  const [revealed, setRevealed] = useState(Array(cards.length).fill(false));
  const [selectedCard, setSelectedCard] = useState(null);

  const handleShuffle = () => {
    setCards(shuffle([...cardsData]));
    setRevealed(Array(cards.length).fill(false)); // Reset revealed state
    setSelectedCard(null); // Close modal if open
  };

  const handleReveal = (index) => {
    setRevealed((prev) =>
      prev.map((item, i) => (i === index ? true : item))
    );
    setSelectedCard(cards[index]); // Open modal with the selected card
  };

  const handleCloseModal = () => {
    setSelectedCard(null);
  };

  return (
    <div className="App">
      <h2>How is your Destiny Today?</h2>
      <div className="card-container">
        {cards.map((card, index) => (
          <Card
            key={index}
            image={card.image}
            isRevealed={revealed[index]}
            onClick={() => handleReveal(index)}
          />
        ))}
      </div>
      <button onClick={handleShuffle} className="shuffle-button">
        Shuffle Cards
      </button>
      {selectedCard && (
        <Modal card={selectedCard} onClose={handleCloseModal} />
      )}
    </div>
  );
}

export default App;
